language: cpp
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
      addons:
        apt:
          packages:
            - build-essential
            - pkg-config
            - cmake
      before_install:
        - sudo apt-add-repository --yes ppa:beineri/opt-qt593-trusty
        - sudo apt-get -qq update
      install:
        - sudo apt-get --yes install build-essential automake autoconf libtool pkg-config cmake
        - sudo apt-get --yes install qt59-meta-full
      before_script:
        - QTDIR="/opt/qt59"
        - PATH="$QTDIR/bin:$PATH"
        - source /opt/qt59/bin/qt59-env.sh
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      before_install:
        - brew update
      install:
        - brew install qt5
      before_script:
        - QTDIR="/usr/local/opt/qt"
        - LDFLAGS="-L$QTDIR/lib:$LDFLAGS"
        - CPPFLAGS="-I$QTDIR/include:$CPPFLAGS"
        - PKG_CONFIG_PATH="$QTDIR/lib/pkgconfig:$PKG_CONFIG_PATH"
        - PATH="$QTDIR/bin:$PATH"
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
after_script:
  - ctest
before_deploy:
  - cpack
deploy:
  skip_cleanup: true
