#ifndef __FDOTOOL_SETTINGS_DEFAULTS_H
#define __FDOTOOL_SETTINGS_DEFAULTS_H

#define SETTINGS_PKCSTOOL_BIN_DEFAULT ""
#define SETTINGS_PKCSENGINE_LIB_DEFAULT ""
#define SETTINGS_OPENSSL_BIN_DEFAULT ""
#define SETTINGS_SMARTCARD_PRODUCER_DEFAULT ""
#define SETTINGS_SMARTCARD_LIB_DEFAULT ""
#define SETTINGS_CERTIFICATE_ID_DEFAULT ""

#define SETTINGS_SMARTCARD_PRODUCER_ATHENA "athena"
#define SETTINGS_SMARTCARD_PRODUCER_INCARDOBERTHUR "incardoberthur"

#endif
